<li>
              <div class='menu-info'>
                <div class='info-triangle'></div>
                <div class='info-perview'>
                  <div id="bdshare" class="bdshare_t bds_tools get-codes-bdshare">
                    <a class="bds_qzone"></a>
                    <a class="bds_tsina"></a>
                    <a class="bds_tqq"></a>
                    <a class="bds_renren"></a>
                    <a class="bds_douban db"></a>
                    <a class="bds_sqq sqq"></a>
                    <a class="bds_kaixin001 kxw"></a>
                    <a class="bds_fbook facebook"></a>
                    <a class="bds_twi twitter"></a>
                    <span class="bds_more"></span>
                  </div>
                  <a href='[field:arcurl/]'><img src='[field:picname/]' /></a>
                </div>
                <div class='info-inner'>
                  <h3><span>[ <a href='[field:field.officialdemo/]'>交互式页面</a> ]</span>[field:title/]</h3>
                  <div class='inner-brief'>
                    [field:description function="cn_substr(@me,120)"/]... 
                  </div>
                  
                  <a href='[field:arcurl/]'>
                  <div class='inner-enter'>
                      <div class='enter-btn'>
                          <p>点击阅读</p>
                          <i>&#xe672;</i>
                      </div>
                  </div>
                  </a>
                  <div class='inner-dialog'>
                    <div class='time'>
                      <i>&#xe63a;</i>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]  
                    </div>
                    <div class='another'>
                      <ul>
                        <li><i>&#xe83e;</i>[field:click/] </li>
                        <li><i>&#xe611;</i>[field:scores/] </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div class='menu-timeAxis'>
                <div class='timeAxis-topLine line'></div>
                <div class='timeAxis-ball'><span></span><p class='time'>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</p></div>
                <div class='timeAxis-bottomLine line'></div>
              </div>
            </li>